/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CloseBtn: typeof import('./src/components/CloseBtn.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DTAsteroid: typeof import('./src/components/DTAsteroid.vue')['default']
    DTMine: typeof import('./src/components/DTMine.vue')['default']
    DTPlanet: typeof import('./src/components/DTPlanet.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
    QueryIcon: typeof import('./src/components/QueryIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
